# Generated by Django 4.1.4 on 2022-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('orginal_title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rated', models.CharField(blank=True, max_length=255, null=True)),
                ('released', models.CharField(blank=True, max_length=255, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('ratings', models.TextField(blank=True, null=True)),
                ('metascore', models.PositiveIntegerField(blank=True, null=True)),
                ('imdbrating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('imdbid', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ManyToManyField(blank=True, related_name='actors', to='storage.cast')),
                ('director', models.ManyToManyField(blank=True, related_name='directors', to='storage.cast')),
                ('writer', models.ManyToManyField(blank=True, related_name='writers', to='storage.cast')),
            ],
        ),
    ]
