# Generated by Django 4.1.4 on 2022-12-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ratings',
        ),
    ]
