# Generated by Django 4.1.4 on 2022-12-28 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_rename_actor_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='storage.list')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listitems', to='storage.movie')),
            ],
        ),
    ]
