# Generated by Django 4.1.4 on 2022-12-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_list_listitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listitem',
            unique_together={('list', 'movie')},
        ),
    ]
