# Generated by Django 4.1.4 on 2022-12-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
