# Generated by Django 4.1.4 on 2023-01-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_list_user_list_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
