# Generated by Django 4.1.4 on 2023-01-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_movie_imdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
