# Generated by Django 4.1.4 on 2023-01-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_list_created_at_movie_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='storage.genre'),
        ),
    ]
